import torch
from datasets import load_dataset
from .tokenizer import HyperTokenizer

class TinyStoriesDataLoader:
    """
    Downloads and streams the 'roneneldan/TinyStories' dataset from HuggingFace.
    TinyStories consists of simple English stories generated by GPT-3.5/4 that only use 
    words typical of a 3 to 4-year-old child. This dataset perfectly proves grammar 
    acquisition on small (1M-50M) networks without requiring world knowledge.
    """
    def __init__(self, batch_size=16, seq_len=128):
        self.tokenizer = HyperTokenizer()
        self.batch_size = batch_size
        self.seq_len = seq_len
        
        print("Loading a tiny chunk of TinyStories dataset...")
        # Load a deterministic 10,000 row block (only takes seconds)
        self.dataset = load_dataset("roneneldan/TinyStories", split="train[:10000]")
        self.vocab_size = self.tokenizer.vocab_size
        
    def stream_batches(self, max_batches=None):
        """
        Yields batches of (X, Y) where X is the sequence and Y is the next token.
        It continuously pulls stories, concatenates them, and yields blocks of `seq_len`.
        """
        current_batch_X = []
        current_batch_Y = []
        batch_count = 0
        
        # We hold a running buffer of tokens to chop into identical `seq_len` chunks
        token_buffer = []
        
        for sample in self.dataset:
            text = sample['text']
            # Encode text to token IDs
            tokens = self.tokenizer.encode(text)['input_ids'][0].tolist()
            token_buffer.extend(tokens)
            
            # While we have enough tokens to form a sequence (+1 for the target prediction)
            while len(token_buffer) >= self.seq_len + 1:
                seq_chunk = token_buffer[:self.seq_len + 1]
                token_buffer = token_buffer[self.seq_len:] # Standard sliding window could step 1, but we jump `seq_len` for speed
                
                # Split into Input (X) and Target (Y)
                X = seq_chunk[:-1]
                Y = seq_chunk[1:]
                
                current_batch_X.append(X)
                current_batch_Y.append(Y)
                
                # Yield when we hit the total batch size
                if len(current_batch_X) == self.batch_size:
                    batch_X_tensor = torch.tensor(current_batch_X, dtype=torch.long)
                    batch_Y_tensor = torch.tensor(current_batch_Y, dtype=torch.long)
                    
                    yield batch_X_tensor, batch_Y_tensor
                    batch_count += 1
                    
                    current_batch_X = []
                    current_batch_Y = []
                    
                    if max_batches and batch_count >= max_batches:
                        return
